app/core/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired

class WordForm(FlaskForm):
    word = StringField(
        'Word',
        validators = [DataRequired()]
    )

    submit = SubmitField('Search')

app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.ProductionConfig')

    from .core.routes import blueprint as core_bp
    app.register_blueprint(core_bp)
    
    return app

app/core/routes.py
from flask import Blueprint, render_template, request, flash
from .forms import WordForm
from typing import List
import requests

blueprint = Blueprint('core', __name__, template_folder = 'templates')


@blueprint.route('/', methods = ['GET', 'POST'])
def index():
    form = WordForm(request.form)

    if form.validate_on_submit():
        data = lookup_word(form.data.get('word'))

        if data:
            return render_template('index.html', data = data, form = form)

    return render_template('index.html', form = form)


@blueprint.route('/test')
def test():
    word = 'WORLD'

    return f'<h1>HELLO {word}</h1>'


def lookup_word(word: str) -> dict:
    r = requests.get(f'https://api.dictionaryapi.dev/api/v2/entries/hi/{word}')
    
    if r.status_code == 200:
        data = r.json()
        return data
    else:
        flash('An error occurred')

app/templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Hindi Dictionary</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>

<body>

    <div class="container">

        <main>
            <div class = 'jumbotron mt-5'>
                <h1>Siddhant's Website</h1>
                <p class = 'lead'>
                    Welcome to my Website
                </p>
            </div>
            
            <div>
                <h2>Dictionary: </h2>
                <form action = "{{ url_for('core.index') }}" method = 'POST'>
                    {{ form.csrf_token }}
                    {{ form.word }}
                    {{ form.submit }}
                </form>

                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <p class = 'text-danger'>{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                {% if data %}
                    <table class="table table-striped mt-5">
                        <thead>
                            <tr>
                                <th scope="col">Word</th>
                                <th scope = 'col'>Type</th>
                                <th scope="col">Origin</th>
                                <th scope="col">Definition</th>
                            </tr>
                        </thead>

                        <tbody>
                            
                            {% for word in data %}
                            {% for meaning in word.get('meanings') %}
                                <tr>
                                    <td>{{ word.get('word') }}</td>
                                    <td>{{ meaning.get('partOfSpeech') }}</td>
                                    <td>{{ word.get('origin', 'There is no origin to display') }}</td>

                                    <td>
                                            {% for definition in meaning.get('definitions') %}
                                                {% if definition %}
                                                    {{ definition.get('definition') }}<br>
                                                {% else %}
                                                    There is no definition to display
                                                {% endif %}
                                            {% endfor %}
                                        </td>
                                        
                                </tr>
                                {% endfor %}
                            {% endfor %}

                        </tbody>
                    </table>
                  {% endif %}
            </div>

        </main>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
    <script>
        Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
        });
    </script>
</body>

</html>

app/templates/test.html
<h1>HELLO</h1>